version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-user.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27017:27017"
    networks:
      - appnet

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: my-app
    depends_on:
      - mongo
    restart: on-failure
    environment:
      # 在 admin 库进行认证
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/mydatabase?authSource=admin"
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
